from course import Course
from university import University
from intake import Intake
from sportmale import SportMale
from sportfemale import SportFemale
from reason import Reason
from video import Video
from linkedin import LinkedIn
from ranking import Ranking
